<a href="https://colab.research.google.com/github/Natassiam/jpy/blob/master/Copy_of_Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import random
import numpy as np

grupo2 = [42,66,33,44,55]



In [0]:
macro_list = []
macro_list.append(grupo2)



In [41]:
print(macro_list)

[[42, 66, 33, 44, 55]]


In [42]:
random.shuffle(grupo2)
print(grupo2)

[55, 66, 33, 44, 42]


In [0]:
def embaralhar():
 for sorteio in grupo2(1,10):
  random.shuffle(grupo2)


In [95]:
grupo = np.arange(0,30)
print(grupo)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [96]:

grupo = grupo.reshape(5,6)[::-1]
print(grupo)



[[24 25 26 27 28 29]
 [18 19 20 21 22 23]
 [12 13 14 15 16 17]
 [ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]]


In [0]:
random.shuffle(grupo)

In [98]:
print(grupo)

[[24 25 26 27 28 29]
 [18 19 20 21 22 23]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [ 6  7  8  9 10 11]]


In [110]:
nomesHerois = ["Stark","Batman", "Captan", "Aranha", "Venom","Ciclope"]
random.shuffle(nomesHerois)
print(nomesHerois)

['Captan', 'Venom', 'Aranha', 'Ciclope', 'Stark', 'Batman']
